apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.cart.name }}
  labels:
    app.kubernetes.io/name: "{{ .Values.config.cart.name }}"  
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"   
spec:
  type: {{ .Values.cart.service.type }}
  ports:
  - port: {{ .Values.config.cart.externalPort }}
    targetPort: {{ .Values.config.cart.internalPort }}
    protocol: TCP
    name: {{ .Values.cart.service.name }}
  selector:
    app: {{ .Values.config.cart.name }}
