apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite
spec:
  selector:
    matchLabels:
      app: satellite
  template:
    metadata:
      labels:
        app: satellite
      # annotations:
      #   sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: server
          image: satellite
          ports:
          - containerPort: 8360
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_ready"
              port: 8361
              httpHeaders:
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_live"
              port: 8361
          env:
          - name: COLLECTOR_API_KEY
            value: "eyJhbGciOiJIUzI1NiIsImtpZCI6IjIwMTktMDMtMDEiLCJ0eXAiOiJKV1QifQ.eyJzY29wZSI6eyJjb2xsZWN0b3IiOnsicmVhZHdyaXRlIjp0cnVlfX0sImF1ZF9pZCI6IjEyOWY2ZWIzNGE3ZGJjZDcxZTI2NDM1Yzc4OSIsImF1ZCI6IkxpZ2h0U3RlcCIsImV4cCI6MTU5OTA5MDk0NCwianRpIjoiZGJkeWJyemlpbzMzbm16d3hzdHl0MjY3cW1kamp4bzZ4d2NzYTQ0b25kbG1qejVvIiwiaWF0IjoxNTY3NTU0OTQ0LCJpc3MiOiJsaWdodHN0ZXAuY29tIn0.O-7_fQJOm8GcQ_OB2xqgHnLjAOH9GYLbLwX74f5GbD8"

          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: satellite
spec:
  type: ClusterIP
  selector:
    app: satellite
  ports:
  - name: http
    port: 8360
    targetPort: 8360
---
apiVersion: v1
kind: Service
metadata:
  name: satellite-external
spec:
  type: LoadBalancer
  selector:
    app: satellite
  ports:
  - name: http
    port: 8360
    targetPort: 8360