on:
  pull_request_review:
    types: [submitted]

jobs:
 deploy_check_job:
   runs-on: ubuntu-latest
   name: Verify Pre-Deploy Status

   steps:  
     - name: Checkout
       uses: actions/checkout@v2

     # Run checks
     - name: Lightstep Pre-Deploy Check
       id: lightstep-predeploy
       uses: lightstep/lightstep-action-predeploy
       with:
         lightstep_api_key: ${{ secrets.LIGHTSTEP_API_KEY }}
         pagerduty_api_token: ${{ secrets.PAGERDUTY_API_TOKEN }}
         rollbar_api_token: ${{ secrets.ROLLBAR_API_TOKEN }}

     # Output status as PR comment
     - name: Add PR Comment
       uses: unsplash/comment-on-pr@master
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         msg: ${{ steps.lightstep-predeploy.outputs.lightstep_predeploy_md }}
         check_for_duplicate_msg: true
